;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Fri Apr 17 2026
; Processor: PIC16F628A
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p16f628a.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================
COUNTER EQU 0x70 ; this variable is for calling "WAIT" 0xFF times and saving space instead of using too many NOP instruction, also creating time for reading the input
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start

;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start
      BCF STATUS, C ; clearing carry flag
      MOVLW 0x01 ; 0000 0001
      MOVWF PORTB ; 0. bit's led set on
      
      MOVLW 0x07
      MOVWF CMCON ; digital input
      
      BANKSEL TRISB ; select bank1
      CLRF TRISB ; all pins are output
      MOVLW 0xFF ; 1111 1111
      MOVWF TRISA ; all pins are input
      BANKSEL PORTB ; select bank0

      
; ===== DEFAULT PATTERN (MODE 1) =====
SHIFTLEFT:
      RLF PORTB ; rotate left
      
      BTFSC STATUS, C
      BSF PORTB, 0 ; set 0th bit's LED on
      BTFSC STATUS, C
      BCF STATUS, C ; this way we instantly see the carry bit on PORTB's 0th bit, seeing all LEDs off bugged me
      
      CALL DELAYOFSHIFTLEFT
      CALL DELAYOFSHIFTLEFT ; wait before repeating, makes it easy to keep tracking the LED pattern
      
      GOTO SHIFTLEFT
      
DELAYOFSHIFTLEFT:
      MOVLW 0xFF
      MOVWF COUNTER ; for calling 35 NOP instruction 255 times, saving space. also creating more time for reading the input
SHIFTLEFTDELAYLOOP:
      CALL WAIT ; mini delay
      BTFSC PORTA, 0
      GOTO RELEASEFORCHAOS ; activate mode 2 (chaos) if button is pressed
      DECFSZ COUNTER, 1
      GOTO SHIFTLEFTDELAYLOOP ; loop until [COUNTER] = 0
      RETURN

 RELEASEFORCHAOS:
      BTFSC PORTA, 0
      GOTO RELEASEFORCHAOS ; loop until button is released
      
      BCF STATUS, C ; clearing carry flag
      MOVLW 0x80 ; 1000 0000
      MOVWF PORTB ; 7th bit's LED set on
      
      GOTO CHAOS

; ===== CUSTOM PATTERN (MODE 2)=====
CHAOS:
      RRF PORTB ; this time rotate left
      COMF PORTB, 1 ; and invert
      
      CALL DELAYOFCHAOS ; more delay is necessary for human eye keeping track of the "chaotic" alternating pattern
      CALL DELAYOFCHAOS
      CALL DELAYOFCHAOS
      CALL DELAYOFCHAOS
      CALL DELAYOFCHAOS
      CALL DELAYOFCHAOS
      
      COMF PORTB, 1 ; invert to normal
      RRF PORTB ;  rotate again
      
      BTFSC STATUS, C
      BSF PORTB, 7 ; set 7th bit's LED on
      BTFSC STATUS, C
      BCF STATUS, C ; this way we instantly see the carry bit on PORTB's 0th bit, seeing all LEDs off bugged me
      
      CALL DELAYOFCHAOS ; more delay is necessary for human eye keeping track of the "chaotic" alternating pattern
      CALL DELAYOFCHAOS
      CALL DELAYOFCHAOS
      CALL DELAYOFCHAOS
      CALL DELAYOFCHAOS
      CALL DELAYOFCHAOS
      
      GOTO CHAOS
      
DELAYOFCHAOS:
      MOVLW 0xFF
      MOVWF COUNTER; for calling 35 NOP instruction 255 times, saving space. also creating more time for reading the input
CHAOSDELAYLOOP:
      CALL WAIT ; mini delay
      BTFSC PORTA, 0
      GOTO RELEASEFORSHIFTLEFT ; activate mode 1 (default) if button is pressed, wanted to implement this
      DECFSZ COUNTER, 1
      GOTO CHAOSDELAYLOOP ; loop until [COUNTER] = 0
      RETURN
      
 RELEASEFORSHIFTLEFT:
      BTFSC PORTA, 0
      GOTO RELEASEFORSHIFTLEFT ; wait until button release
      
      BCF STATUS, C ; clearing carry flag
      MOVLW 0x01 ; 0000 0001
      MOVWF PORTB ; 0th bit's LED set on
      
      GOTO SHIFTLEFT
      
   WAIT: ; just for saving space
      NOP
      NOP
      NOP
      NOP
      NOP
      
      NOP
      NOP
      NOP
      NOP
      NOP
      
      NOP
      NOP
      NOP
      NOP
      NOP
      
      NOP
      NOP
      NOP
      NOP
      NOP
      
      NOP
      NOP
      NOP
      NOP
      NOP
      
      NOP
      NOP
      NOP
      NOP
      NOP
      
      NOP
      NOP
      NOP
      NOP
      NOP
      
      RETURN
      
;====================================================================
      END
